### PR TITLE
Task: Add pruning docs to README

### PR DESCRIPTION
**Pull request by robinjmurphy**
@DaMouse404 @scripter-co What do you reckon?

Thought it would be good to document.

### CODE REVIEW

**Comment by scripter-co** [comment]
@robinjmurphy Looks good to me. It's definitely something that should be documented; we've had two different projects start to fail building due to some weird limitation on files count/inodes.

👍

**Comment by DaMouse404** [comment]
Might be good to highlight the issue we found where it was actually the sheer amount of files in the RPM which caused the build to fail rather than the issue of the RPM being too big? That at least gives someone a heads up that it might happen with the number of files npm can create.

**Comment by fewstera** [comment]
@robinjmurphy you could run `npm prune --production` as a build step prior to `npm rebuild` then you don't need to worry about reinstalling speculate.

**Comment by robinjmurphy** [comment]
@fewstera We did think about that, but in some cases you actually want the dev dependencies. For example, we have a project where we need coffee-script at runtime.

**Comment by robinjmurphy** [comment]
We wanted to leave it up to the developer, but maybe it could be an option.

**Comment by robinjmurphy** [comment]
Will merge the docs for now but we could think about a prune option.

**Pull request merged**
