### PR TITLE
add inline support to specify environment variables

### PR DESCRIPTION
**Pull request by vtervo**

### CODE REVIEW

**Comment by robinjmurphy** [comment]
Hi @vtervo. This is a nice feature.

I think I prefer specifying the environment is using an object. What do you reckon?

```json
{
  "spec": {
    "environment": {
      "NODE_ENV": "prod",
      "FOO": "bar"
    }
  }
}
```

**Comment by vtervo** [comment]
Sounds good to me. I'll edit PR to use an object instead of an array.

**Comment by robinjmurphy** [comment]
Thanks for updating @vtervo.

Do you mind updating the configuration property to be `environment` rather than `envVars`? It just means that it matches the SystemdD directive a bit more closely. 

I just have one question before merging.

Are you going to be deploying your RPM-packaged application to multiple environments? (e.g. staging/production)

Just checking because using this feature wouldn't work as well if you needed to change the environment variables on a per-environment basis.

**Comment by vtervo** [comment]
No problem. I missed envVars vs. environment in your previous comment. 
Updated version coming in soon.

No I'm not differentiating staging/production with environment systemd variable.

But I'm tinkering to add support for instantiated service files. I could then bring in instance name to node process using environment.

**Comment by robinjmurphy** [comment]
Releases as 1.4.0.

**Pull request merged**
